### ISSUE TITLE
UnsupportedOperationException from Curios API following Elemental Might advancement

### ISSUE THREAD

**Issue by duely** [Extegral/Enigmatic-Legacy#10]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.6.1
 * Curios API: curios-FORGE-1.14.4-1.0.3 (I think this is the API)
 * Forge: 28.1.44

#### Description of a Bug:
Upon achieving the advancement "Elemental Might" the server crashed with an UnsupportedOperationException from the Curios capability. I'm not sure whose side the issue is on, or if it's potentially related to other mods installed on the server.

#### How to Reproduce:
1. Have not yet tried to reproduce

#### Logs:

Crash Log: https://gist.github.com/duely/6b9d91bd088c7dfa49b5512abbcc3c5f

(Contains crash report & the tail end of latest.log just after the server went down)

**Comment by Extegral** [comment]
Your issue is completely identical to #9.

This bug turned out to be quite inconsistent and hard to reproduce. I cannot see how this could be caused on my side, since the crash happened after simply calling a method from Curios API, while all passed arguments are doubtlessly correct.

Go to [issue tracker of Curios](https://github.com/TheIllusiveC4/Curios/issues) and report it there.

**Comment by duely** [comment]
That's fine, I've already reported it directly to the author of Curios as well -- I figured I'd report it in both places. Unfortunately it happened quite late for me and I didn't think to check to see if it had already been reported -- my bad.

**Comment by duely** [comment]
This has been fixed on the Curios end.
