### ISSUE TITLE
Mod combatibility request

### ISSUE THREAD

**Issue by Gabo6480** [Extegral/Enigmatic-Legacy#103]
Just wanted to ask you to try and make the enchantment features combatible with other enchantment mods, I tried to use the new Enchanters Pearl with the mod Apotheosis and doesn't seem to work at all, also the extra 10 levels of enchantment form the ring of the seven curses also seem to only rise the enchantment price without modifying the results

**Comment by Aizistral** [comment]
The pearl of course isn't gonna work as it stands, because what most of those mods to is that they completely replace GUI and container of vanilla enchanting table, while to make pearl work all I could do was either hook into vanilla version of that container to overwrite the enchanting process in an instance if player has that pearl, or replace the container entirely similar to how those mods do, and the latter would've made things even less compatible than they are currently. I will look into whether or not I can do something reasonable on my side to make it work with Apotheosis, but it certainly isn't possible without mod-specific compat. Just so that you are aware that I can't just take it and make it compatible with every mod that modifies vanilla enchanting out there.

**Comment by Aizistral** [comment]
I have made separate mixin to handle the container of Apotheosis, apart from having to create separate ruleset for rolling additional enchantments and merging them onto original item in an instance with Apotheosis in play, because all of that overleveling wouldn't have gone along well with vanilla rules. The only concern is that I can't invoke advancement trigger when enchanting with the pearl, partially because of issues outlined here: https://github.com/Shadows-of-Fire/Apotheosis/issues/250

I expect @Shadows-of-Fire to change their trigger implementation, and then perhaps this can be addressed.

Regarding this:
> also the extra 10 levels of enchantment form the ring of the seven curses also seem to only rise the enchantment price without modifying the results

This is something that must be handled on the side of Apotheosis, because enchantment level is modified through Forge's `EnchantmentLevelSetEvent`, which they should respect with their enchanting implementation. If you have confirmed evidence that increased level doesn't change the result, report this to https://github.com/Shadows-of-Fire/Apotheosis/issues. You can refer to this issue as your initial report and to my reply on this case here.
