### ISSUE TITLE
Loot won't generate in some structures (modpack) 1.16.4

### ISSUE THREAD

**Issue by Blugori** [Extegral/Enigmatic-Legacy#109]
* Enigmatic Legacy: 2.10.0
 * Curios API: 4.0.2.1
 * Patchouli: 1.16.2-47
 * Forge: 35.1.0

Hi !
When I created a new world after installing enigmatic legacy and found a desert temple, chests were empty. This has a very high chance to be a compatibility between mods issue, but even after a lot of tries, I couldn't found the "culprit" mod, I was hoping you could give me a hint on this, since it was working fine without enigmatic legacy (but using enigmatic legacy alone wont bring that problem).

[debug.log](https://github.com/Extegral/Enigmatic-Legacy/files/5580026/debug.log)
[latest.log](https://github.com/Extegral/Enigmatic-Legacy/files/5580027/latest.log)

link for the modpack : https://we.tl/t-fLKbWFShas

list of mods : https://pastebin.com/bDyCqJ24

Best regards !

**Comment by Aizistral** [comment]
From your log I can tell that some other mod is once again making an error of injecting unnamed `LootPool` into loot tables, and there are some more tables affected than just Desert Temple, but I can't tell what mod is doing this.

You can try going through all of the mods in your modpack which you know are adding some dungeon loot, disabling them one-by-one and loading up test world without them to check out whether issue persists. You can use The One Box added by Enigmatic Legacy itself to test whether loot is generated in any given table.

If that doesn't help, that unfortunately means you'll have to try and keep splitting you modlist in two, until you narrow the search down to specific mod causing trouble. Once you know what exact mod causes it you can report the issue to it's developers, or let me do this as I will be able to point out what specific change is required in their code and where.

In next update I plan to add some log output that will allow to more easily indicate when unnamed LootPools are injected and what mod is dumb enough to do it when that happens, since this is not the first such case reported, but it might be a while until it's released.

**Comment by Blugori** [comment]
Oh that's great news ! I'll let you know if I can find the wrong mod, and if I can't I'll be patient ! (Should I close this issue for now ?)

**Comment by Aizistral** [comment]
> Should I close this issue for now?

Don't hurry. We can close it once the mod responsible is known and report is made to a person or team that maintains it.

**Comment by Blugori** [comment]
Ok I actually achieved to isolate the culprit, that was hard 😅
So if you want to have a look, my config is :

Minecraft : 1.16.4
Forge : 35.1.0
Enigmatic Legacy : 2.10.0
Patchouli : 1.16.2-47
Optifine : 1.16.4_HD_U_G5
Omni : 1.1.0

Latest logs : 
[debug.log](https://github.com/Extegral/Enigmatic-Legacy/files/5585036/debug.log)
[latest.log](https://github.com/Extegral/Enigmatic-Legacy/files/5585037/latest.log)

I'll open an issue on the Omni mod github page too !

**Comment by Blugori** [comment]
Oh and if you don't mind giving a clue for the creator that would be great, I believe "Omni" is a recent project, the creator might be a "newcomer" 🙂

https://github.com/c0d3break3r/Omni/issues/23

**Comment by Aizistral** [comment]
Great work. I already commented there to point out what they need to fix on their side, all we have left to do is just wait for their response. Closing this now.

**Comment by Blugori** [comment]
Thanks for your help !
