### ISSUE TITLE
Crash on startup with Hunter Illager

### ISSUE THREAD

**Issue by CesarDavidXI** [Extegral/Enigmatic-Legacy#115]
-->

#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.10.1
 * Curios API: 4.0.3.0
 * Patchouli: 1.16.4-48
 * Forge: 35.1.7

#### Description of a Bug:
So, im creating an aventure rpg modpack for 1.16.4 with tons of hours to play with, and it was working perfectly until i saw your mod and how ir fits perfectly in the modpack theme and wanted to implement it.
Crashes upon early fml loading after deseo scanning all the mods, it prompts unexpected issue and Exit Code; 0.
Went into the log and saw a fatal error that wasn't prompting before with Hunter Illager whenever I added this mod.

#### How to Reproduce:
1. Use the current versions of this mod and "Hunter Illager"
2. It Crashes with a fatal error
3. ...
4. Behold!

#### Logs:

Crash Log: https://pastebin.com/rimufFM5

**Comment by Aizistral** [comment]
This would require a change on the side of that mod, since they apparently use Mixin to modify vanilla crossbow methods, but never assume `private` methods in that crossbow could be access transformed to be `public`. Report it to maintainers of Hunter Illager and point back to this issue as your original report if neccessary.

**Comment by DamienBrittan** [comment]
ha , i am making just the same mod pack and having the same exact problem as u do xD that's something !
