### ISSUE TITLE
Enigmatic Legacy and Corail Tombstone Loot Table NPE

### ISSUE THREAD

**Issue by Anuuviem** [Extegral/Enigmatic-Legacy#12]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.6.2
 * Curios API: 1.0.5.3
 * Forge: 28.1.90

#### Description of a Bug:
Corail Tombstone and Enigmatic Legacy, when paired together, produce a loot table NPE that causes dungeon/abandoned mine loot to not generate
#### How to Reproduce:
1. Install versions listed above
2. Get on server
3. Hunt down a dungeon or abandoned mine
4. Behold! No loot in containers

#### Logs:
https://pastebin.com/JXSQHQF3

I am "stoopid" excited to play with your mod, I hope these errors can be resolved and I appreciate the work you lovingly put into this game!

**Comment by Corail31** [comment]
The npe is often because a mod (yours) is adding loottables with no name if it helps to solve this (tombstone doesn't have this trouble)

**Comment by Extegral** [comment]
The problem is that my mod doesn't have unnamed loottables. It is visible in [event handler](https://github.com/Extegral/Enigmatic-Legacy/blob/master/src/main/java/com/integral/enigmaticlegacy/handlers/EnigmaticEventHandler.java#L670), which does use [constructLootPool method](https://github.com/Extegral/Enigmatic-Legacy/blob/master/src/main/java/com/integral/enigmaticlegacy/handlers/SuperpositionHandler.java#L380), which does always take argument for constructed pool name.

I will soon adress this, but so far I cannot see how my mod could be the cause of this issue.

**Comment by Corail31** [comment]
@Extegral hello :)
The trouble with names of this issue was perhaps in another mod but most of them fixed their code since, so probably the issue can be closed.
I also made some tests with your mod and mine in 28.2.4 (1.14.4) and the drops were present in the lootables.

**Comment by Extegral** [comment]
Ok
