### ISSUE TITLE
wyrmroost crash on world creation

### ISSUE THREAD

**Issue by imthekiduknowwhatimean** [Extegral/Enigmatic-Legacy#129]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.10.3
 * Curios API: 1.16.4-4.0.3.3
 * Patchouli: 1.16.4-48
 * Forge: 35.1.36
 * Wyrmroost: 1.16.3-1.2.10 (current latest)

#### Description of a Bug:
Crash at the end of world creation.
weird as the 2 mods worked together before. change could be either forge version or update to one or both of the mods.

#### How to Reproduce:
1. create a 1.16.4 forge 35.1.36 profile
2. install above listed versions of enigmatic legacy and wyrmroost (current latest version januray 8 2021)
3. start game and create world 
4. Behold!

#### Logs: https://hastebin.com/poluzuriha.sql

Crash Log: https://hastebin.com/ipibeginip.properties

**Comment by Aizistral** [comment]
The original cause of this on the side of Wyrmroost: https://github.com/WolfShotz/Wyrmroost/issues/203

They have fixed it already, but next release is not build yet. The reason it crashes is because Wyrmroost does inject unnamed `LootPool`s into some loot tables, and Enigmatic Legacy has handler specifically designed to detect when that happens as of 2.10.3 (since it leads to bugs with no loot being generated from such tables later, empty dungeon chests and alike). You can disable that handler by disabling `CrashOnUnnamedLootPool` option in Enigmatic Legacy's config if you don't want it.

**Comment by noobanidus** [comment]
I'm hopeful a patch to Forge will be made, as this inherently an issue with their code. The name field is null by default, and while the builder does have the `name` method to add a name, it's not *required*. However, their validation code assumes that the name is `NotNull` and performs a `String::equals` check, resulting in the crash. Ideally it should just check for null and skip those pools, or enforce a name (harder as it requires a bigger patch), or auto-generates a name (likewise difficult). 

EDIT: I think this is potentially a hang-over from previous versions where loot pool names were required. I do seem to remember filing a bug about it with Forge though, but it's another one from the 1.14 era (the other being the issue with getMappings which was only just patched) that seems to have slipped through the cracks.

Frankly this is something that has been around since the very, very early days of 1.14 and it's quite frustrating to realise that it still hasn't been resolved after a) causing it myself with Mystical World, and b) haven't to troubleshoot all the times where people come to me when it's not my loot pool that's the issue.

**Comment by Aizistral** [comment]
> Frankly this is something that has been around since the very, very early days of 1.14 and it's quite frustrating to realise that it still hasn't been resolved

Oh well, so relatable.

> having to troubleshoot all the times where people come to me when it's not my loot pool that's the issue

Over this I have just shed a tear.

I also hope Forge guys will fix it at some point, but judging how easily they gloss over minor (for them) issues like this one, it's quite possible to take a couple more major MC before we finally see it happening.

In theory I could just as well have made a handler in my mod that patches this problem instead of just helping to debug it, but that's a lot like trying to cure symptom instead of dealing with actual disease. It unfortunately still needs to be and can only be properly fixed on the side of Forge itself.

**Comment by Aizistral** [comment]
Should be fixed as of latest versions of Wyrmroost.
