### ISSUE TITLE
[Suggestion] Tweaks for Angel's Blessing

### ISSUE THREAD

**Issue by alpharou** [Extegral/Enigmatic-Legacy#170]
In its current form the Spellstone works fine, but its active ability feels a little lackluster.

- **Reducing its cooldown/tweak the power and direction of the launch**, 
would be nice in my opinion. I find the boost insufficient when using it to fly paired with elytras, to the point that gaining altitude gets tiring, even more if you can't afford to be looking up when dodging obstacles like trees or lava.

- **Assign it an auxiliary keybind (preferably customizable) or an alternative way of triggering the ability**
since it could be useful to be able to activate it with a more convenient key, like pressing space while airborne so that you don't have to reach for the keybind. It would allow for really nice quality of life mechanics (Double jump, easy elytra take off...) without being tedious or overly intrusive.

There are many other items and ways to improve movility in minecraft, it wouldn't hurt so much having a trinket that made you actually go further than a regular jump, provide a safe double jump and be able to fly freely without carrying vanilla rockets.

**Comment by Aizistral** [comment]
The thing with Angel's Blessing is - if you fly using Elytra, it provides the more speed boost the less momentum you already have. Momentum gain declines expotentially the more you accelerate, in order to make it impossible to accelerate infinitely. I have played around with precise adjustments a lot back in the day and stopped exactly at the values which I find most usable for convenient Elytra flight, enough boost to allow you to fly infinitely and increase maneurability, but still requiring some skill to master this form of flight and not forgiving you all possible mistakes. If you don't feel like it works for you, there are a whole two options in the config to adjust Angel's Blessing acceleration, for elytra and non-elytra cases, try to tweak those first.

It must be noted, however, that I use one of my mouse's extra keys as a keybind for Angel's Blessing ability, and I am unfortunately aware not all mouses have extra keys on them. Designing an alternative control scheme here is worth considering, preferrably with an option for player to choose between alternative and original.

**Comment by Aizistral** [comment]
In retrospect, I think letting it work by pressing space while airborne is a really great idea. Will make it happen.

**Comment by Aizistral** [comment]
Done in 2.16.0.
