### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by LinJonKur** [Extegral/Enigmatic-Legacy#172]
When the RotSC is equipped and I mine iron, lapis, redstone , it gives me coal. Is this a normal mechanic of the mod because I couldn't find anything about it. And another thing, when I relog the ring is in my invetory.

**Comment by Aizistral** [comment]
> When the RotSC is equipped and I mine iron, lapis, redstone , it gives me coal. Is this a normal mechanic of the mod because I couldn't find anything about it.

Not, it is not. Might be related to Fortune level increase the ring provides; try to use Charm of the Treasure Hunter in a test world and see if it causes the same effect. If it does, report this to [Curios repository](https://github.com/TheIllusiveC4/Curios/issues), since Enigmatic Legacy uses implementation provided on the side of Curios in order to give some accessories their Fortune/Looting increase abilities.

> And another thing, when I relog the ring is in my invetory.

What you refer to is likely the same issue as described by #159.
