### ISSUE TITLE
Magnetic Ring Effect Given to All Surrounding Players

### ISSUE THREAD

**Issue by viiizee** [Extegral/Enigmatic-Legacy#177]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.11.2
 * Curios API: 4.0.5.0
 * Patchouli: 50
 * Forge: 1.16.5 - 36.1.2

#### Description of a Bug:

On a server, if a player equips a Magnetic Ring into their Curios inventory, the effect is given to all nearby players even if they are not wearing such ring.

#### How to Reproduce:

1. Join a server.
2. Stand near a player
3. Equip a Magnet Ring and have another player try to drop an item.
4. Behold! They can't because the item goes straight back into their inventory.

**Comment by Aizistral** [comment]
It doesn't give them actual effect. What you describe is a result of ring's ability to nullify item pickup delay within it's area of effect; since the mod doesn't try to tell apart where those items are or who will be the first to pick them after, it allows other players to immediately pick back up items they attempt to drop. I'd argue there's no particular reason to alter this behavior, but if you have any arguments, feel free to outline them.
