### ISSUE TITLE
Config to remove Heart of Creation

### ISSUE THREAD

**Issue by Traverse-Joe** [Extegral/Enigmatic-Legacy#189]
I want a config to remove the heart of creation. I would love to keep the item in the pack. Maybe make it a more difficult task.

**I am working on a project for the all the mods team (atm member), the item is quite broken in our pack. It might be perfect with the mod as a whole but in the pack im creating id love a way to disable it a perhaps add it back in a different method**

**Comment by Aizistral** [comment]
Heart of Creation cannot be obtained in survival mode by default.

**Comment by Traverse-Joe** [comment]
No but it’s obtained from seeing the credits with the cursed ring correct?

**Comment by Aizistral** [comment]
> No but it’s obtained from seeing the credits with the cursed ring correct?

I don't know who have told you that, but no. Nobody even suggested me to add such a way of obtaining the heart. There were other suggestions on it, but so far I have rejected them, since as it stands Enigmatic Legacy itself doesn't have deep enough end-game progression as to place an item of such power on top of it. Modpack developers such as you, however, are free to add their own way of obtaining the heart if they see fit.

**Comment by Traverse-Joe** [comment]
Sorry I have a team of testers thanks for all your info and feedback I will do more extensive testing
