### ISSUE TITLE
[Suggest] An ingame book could be really good enhancement

### ISSUE THREAD

**Issue by S0ar1ngDeath** [Extegral/Enigmatic-Legacy#22]
## An ingame book is needed.
---
for long long did I always tab out to just see what does the item do or some information, so an ingame book using some libraries such as _Patchouli_ could been great help, if possible.

**Comment by Extegral** [comment]
Unlikely that I will add this anytime soon. Although I've considered the idea and it's definitely something worth to work over, I don't do much with the mod in latest weeks due to lack of time and inspiration.

I'm planning to come back to it as soon as Forge for 1.15 gets out of beta, to port it there and continue the development on newer version. Support for 1.14 will then likely be reduced to bugfixes and minor changes. 

Just so that you know what to expect.

**Comment by Extegral** [comment]
Will be implemented in 1.16 releases. Now for sure.
