### ISSUE TITLE
How do i equip a spellstone, and Scrolls? I see no slot in the side bar with the rings, and the belts, and i tried the keybinds as well

### ISSUE THREAD

**Issue by Schlokk** [Extegral/Enigmatic-Legacy#228]
**The question.**

**Comment by Aizistral** [comment]
Spellstone and scroll slots are not initially available, however they should be unlocked as soon as you obtain respective accessories that go into these. Also, depending on the amount of mods you have installed you can have more Curios slots than can fit in GUI simultaneously, in which case a scrollbar should appear to allow navigating them. If you already have spellstone or arcane scroll, you can try to use right click when holding them in hand in order to equip them without going through a GUI (although this will not work with Scroll of Ageless Wisdom).
