### ISSUE TITLE
End Loot Not Generating (Modpack)

### ISSUE THREAD

**Issue by zedekblue** [Extegral/Enigmatic-Legacy#23]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.6.2
 * Curios API: FORGE-1.14.4-1.0.6
 * Forge: 1.14.4-28.1.109

#### Description of a Bug:
Loot not generating in End when added to the All The Mods 4 (Forge) ver 0.3.0
https://www.curseforge.com/minecraft/modpacks/all-the-mods-4

Spent over four hours in the end, and tested ~100 chests with The One Box using End_City_Treasure.

Probably an underlying issue with another mod messing with loot tables, but as it stands I can't even begin to hunt down which mod it is. The only affected loot is Enigmatic Legacy.

**Comment by Extegral** [comment]
It can also be caused by any datapack that overrides end_city_treasure loot table.

Such bug commonly happens when some mod adds new loot to loot tables inside it's own datapack, by overriding respective vanilla loot table. My mod, as many others, relies on LootTableLoadEvent for adding new loot, but it never gets fired for overridden loot tables. This seems to be a Forge bug, and it remains unattended for quite a while by now; you can check out respective issue on Forge repository for details: [https://github.com/MinecraftForge/MinecraftForge/issues/6107](https://github.com/MinecraftForge/MinecraftForge/issues/6107)

You can find the mod that causes it by either reviewing the mod files, to see if any of mods in a modpack contains `data\minecraft\loot_tables\chests\end_city_treasure.json`, or you can first take a look at what loot from what mod(s) actually generates in those chests, and then check out respective modfiles.

**Comment by zedekblue** [comment]
Thank you for the suggestions!
Was able to track it down & found an existing issue for it.
https://github.com/stal111/Forbidden-Arcanus/issues/26
