### ISSUE TITLE
Randomly Generated Enigmatic Amulet Color

### ISSUE THREAD

**Issue by Windspren** [Extegral/Enigmatic-Legacy#28]
**Provide a detailed and clear description of feature or change that you want to offer.**
The gemstone in the Enigmatic Amulet could receive a randomly generated color upon spawning, which would be unique to each player. If that's too complex, it could be chosen from a few preset colors, but since many resource packs support random textures I don't think it would be too difficult.

**Describe why you want this. If there's a reason.**
It would be a fun extra bit of flavor and could incentivize people to hold on to their amulets more, as they would be more "personal"

**Comment by Extegral** [comment]
Completely random color would mean, like, 80% chance of getting color that looks like complete shit in combination with amulet's base texture. I think though having a considerable amount of preset colors that choice will be made from certainly isn't a bad idea. Not sure when I will get to this, but in one way or another, this idea will be implemented.

**Comment by Aizistral** [comment]
With some thoughts on this processed, I think I will go for 7 possible colors in total. I have an idea to make every different version of the amulet provide bonus to different stat, apart from it's new Extradimensional Vessel ability, with one of them providing +1.5 armor points for instance instead of +1.5 damage, another one +15% attack speed, something like that.
