### ISSUE TITLE
Angel's Blessing renders player unable to die (even by commands) when used with Blue Skies + Project MMO (1.16.5)

### ISSUE THREAD

**Issue by ChefTheChefChef** [Extegral/Enigmatic-Legacy#289]
#### Versions:
 * Enigmatic Legacy: 2.11.11
 * Curios API: 4.0.8.1
 * Patchouli: 53.2
 * Forge: 36.2.20
 * Blue Skies: 1.1.3
 * Structure Gel API: 1.7.8
 * Project MMO: 3.67.5

#### Description of the Bug:
When loading these mods together, equipping the Angel's Blessing spellstone renders the player immune to damage and functionally immortal by any means, including the /kill command and falling into the void.

#### How to Reproduce:
1. Install the versions of the mods listed
2. Create a new world
3. Find and equip Angel's Blessing (or spawn it in) and use the /kill command, or attempt to die by any means.
4. Behold! You are now unable to die.

#### Logs:

Latest Log: https://www.toptal.com/developers/hastebin/fulofasabi.sql

**Comment by ChefTheChefChef** [comment]
I read in the Project MMO server that someone else had a similar issue; I'm not sure how accurate or helpful this is, but apparently it's a bug with "playerdata ForgeCaps blue_skies:player_capability NatureHealth" where it's set to NaN. That's the reason for immortality, but I think this makes this a Blue Skies issue? See below;
![image](https://user-images.githubusercontent.com/11790731/159402698-9c528ddb-6a02-4b62-9e52-df777e46d998.png)

**Comment by KingPhygieBoo** [comment]
Hey, just passing by and happened to notice this here. I'm a Blue Skies developer, and we actually added a check for this ourselves starting in 1.17 since certain mod interactions would cause this to happen, so the fix shouldn't be needed anymore on your side in versions later than that. If an issue like this comes up again, be sure to report it to us so the real problem can be fixed.

**Comment by Aizistral** [comment]
Thanks for informing me. Will do.
