### ISSUE TITLE
With the RotSC, you can sometime die of poison

### ISSUE THREAD

**Issue by StellaBiscuit** [Extegral/Enigmatic-Legacy#299]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.18.1
 * Curios API: 1.18.2 - 5.0.6.3
 * Patchouli: 1.18.2 - 67
 * Forge: 40.0.36

#### Description of a Bug:
Due to the double damage, the player will die of poison if he has a even amount of hp, if he has an uneven amount of hp, he will survive at 1 hp like in vanilla

If the player regen he is pretty much dead since it will go from 1 to 2 and then kill at 2

#### How to Reproduce:
1. Equip the Ring of the Seven Curses
2. Take poison from any source
3.  If the player has an even amount of hp or he can regen, he will die from the poison, if he has an uneven amount of hp and can't regen, he will survive

To fix this, there 2 solution, either make the poison always letal (and point it out inside of the ring's description), or make it never letal

#### Logs:

No log necessary, it would show nothing anyway

**Comment by Aizistral** [comment]
This is a behavior I am entirely aware of, and it is in fact a direct consequence of how vanilla implements poison - anything that increases damage dealt by it is a subject to such an issue, from this mod or otherwise. I am not sure how neccessary it really is to break status quo on this matter, but I can think of a reasonable workaround.
