### ISSUE TITLE
Possibility to port lockbox content to separate addon mod

### ISSUE THREAD

**Issue by eilamg** [Extegral/Enigmatic-Legacy#313]
Given that

1. this project is otherwise entirely opensource, and
2. the contents of the lockbox are relevant only to a small percentage of users,

I would suggest considering moving the lockbox in its entirety to a separate addon project, available to those who are interested. That way the contents of the lockbox can remain protected in obfuscated binary form and be subject to a more restrictive license, while Enigmatic Legacy can remain a fully open-source project.

This is obviously up to your discretion, and I appreciate the work you've put in either way.

Cheers

**Comment by Aizistral** [comment]
The whole reason I have gone to such lengths with technical and licensing changes was to preserve The Architect's Favor as a part of original mod. It was designed to reward some of the most active members of Enigmatic Legacy's community, but those who cannot or do not wish to be among them will obviously have no reason to install separate addon that adds it, which will largely restrict those who have access to it to using it in singleplayer.

Furthermore, its existence as part of original mod in its previous form inevitably created incentive for altering the mod's code with single intent to change URL from which the list of believers is obtained. I changed the license in order to have legal ability to take action against publication of mod forks which contain such changes, and that part was made closed-source to ensure that alteration is off-limits to people who do not know Java at all or understand it on the level way below what would be needed to create item similar to The Architect's Favor on their own. I have no desire to put similar restrictions upon any other part of the mod, and made every effort to ensure that open-source projects which, while being derived from or incorporating code/assets from Enigmatic Legacy, are actually made in good faith, remain as unaffected by those restrictions as possible.

**Comment by eilamg** [comment]
I figured that was the intention, and I don't disagree with any of the points you make.

The only reason I made the suggestion, is that I'm personally not keen on the inclusion of compiled binaries in an otherwise open source project. As an end user, such a setup means I have to put blind trust in mod developers and the security of their repositories, which makes it functionally (nearly) identical to a closed source project. I've been playing with EL for a while now, and accordingly trust both you and the mod, but that's definitely not the case for most projects out there, and why I'm not a fan of the arrangement.

But like I said, I don't disagree what you wrote, and I fully understand why you would prefer this approach.

Oh, and thanks for clarifying your stance. Many developers would simply ignore or reply with a snide comment. 👍

**Comment by Aizistral** [comment]
Yes, I am certainly aware that having closed-source element in an otherwise open-source project is... not entirely as nice and clean as I would wish it was. I may reconsider the necessity of its presence in such a form in the future, but for now such is the state of things, and my decision is yet firm.

Thanks for understanding my position.
