### ISSUE TITLE
Crash On startup 1.18.2

### ISSUE THREAD

**Issue by keepinitreal247** [Extegral/Enigmatic-Legacy#320]
#### Notice
The Mod seems to work fine on its own but when I put other mods with it crashes I don't know which mods are conflicting with it either so that's why the debug has other mods included

#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: [EnigmaticLegacy-2.21.1.jar]
 * Curios API: curios-forge-1.18.2-5.0.7.0.jar
 * Patchouli: Patchouli-1.18.2-67.jar
 * Forge: forge-1.18.2-40.1.0-installer.jar

#### Description of a Bug:
A clear and concise description of what the issue is.

#### How to Reproduce:
1. Put enigmatic legacy in with its requirements
2. Open Minecraft
3. Press Play
4. Behold!

Debug Log: https://gist.github.com/keepinitreal247/2e55ce5ef5df86e0a91040f8d0b74e05

**Comment by StygianNights** [comment]
I am attempting to recreate, could you please include all mods and versions? The most I have to go off is a list in the debug log which looks like this: 
<details>
<summary>Mod List</summary>
       
> skinlayers3d
> quarryplus
> adlods
> advancementplaques
> alexsmobs
> allthemodium
> ambientenvironment
> appleskin
> architectury
> artifacts
> atlaslib
> autoreglib
> awesomedungeon
> awesomedungeonend
> awesomedungeonnether
> awesomedungeonocean
> balm
> baubles
> betterbiomeblend
> betterf3
> betterthirdperson
> bettervillage
> biomesoplenty
> blueprint
> bookshelf
> buildersaddition
> bygonenether
> carryon
> castle_in_the_sky
> ceilingtorch
> cherishedworlds
> chipped
> citadel
> clickadv
> cloth_config
> cloudstorage
> clumps
> collective
> colossalchests
> comforts
> configured
> connectiblechains
> controlling
> convenientcurioscontainer
> cookingforblockheads
> corpse
> craftingtweaks
> create
> createaddition
> ctm
> curios
> curious_armor_stands
> cdl
> cyclopscore
> darkmodeeverywhere
> darkpaintings
> darkutils
> detailab
> dimdungeons
> ding
> doggytalents
> domesticationinnovation
> doubledoors
> dragonenchants
> dungeoncrawl
> dungeons_arise
> easymagic
> eatinganimation
> effortlessbuilding
> enchantinginfuser
> enchdesc
> enigmaticlegacy,enigmaticlockbox
> equipmentcompare
> etherium
> expandability
> explorerscompass
> farmersdelight
> farmersrespite
> farmingforblockheads
> feature_nbt_deadlock_be_gone
> flowerseeds
> flywheel
> forbidden_arcanus
> forgeendertech
> getittogetherdrops
> guardvillagers
> healthoverlay
> highlighter
> hole_filler_mod
> iceberg
> idas
> infernalmobs
> infinitetrading
> inventoryessentials
> inventoryhud
> inventoryprofilesnext
> invmove
> invmove_compat
> ironchest
> ironfurnaces
> itemzoom
> jade,waila
> jeed
> jei
> justenoughprofessions
> jeresources
> legendarytooltips
> libraryferret
> libx
> lootbagmod
> lucky
> macawsbridgesbop
> maenchants
> mahoutsukai
> mcwbridges
> mcwdoors
> mcwfences
> mcwlights
> mcwpaintings
> mcwtrpdoors
> mca
> dummmmmmy
> more_babies
> more_underground_structures
> morevanillalib
> morevillagers
> mousetweaks
> musicplayer
> mystictools
> naturescompass
> nekoration
> nebs
> nethersdelight
> notenoughcrashes
> oceanfloor
> offhandcombat
> paintings
> patchouli
> pickupnotifier
> piglin_expansion
> pigpen
> placebo
> polymorph
> presencenotrequired
> puzzleslib
> quark
> randomsheepcolours
> rare_ice
> repurposed_structures
> additionalstructures
> ring_of_miner
> runelic
> seamless_loading_screen
> sereneseasons
> shelve
> shrink
> skyvillages
> some_assembly_required
> sophisticatedbackpacks
> sophisticatedcore
> sound_physics_remastered
> supermartijn642corelib
> terrablender
> terraria_paintings
> toastcontrol
> tonsofenchants
> torchslabmod
> torohealth
> tradingpost
> trashcans
> trashslot
> uteamcore
> uncrafted
> uncrafter
> universalenchants
> upgradedcore
> upgradednetherite
> upgradednetherite_items
> usefulbackpacks
> valhelsia_core
> vanillaexcavators
> vanillahammers
> villagertools
> visualworkbench
> windowlogging
> wooltweaks
> worldedit
> worldhandler
> xaerominimap
> xaeroworldmap
> yungsapi
> betterdungeons
> bettermineshafts
> betterstrongholds
> yungsextras
> zetter
> minecraft
> forge

</details>

**Comment by StygianNights** [comment]
Okay, so in recreating this list in a curseforge loader pack, I found a few issues and I am only at the B's

the mods Atlaslib, Baubles, and Better Village are not updated to the correct minecraft versions. I think that you might be having your issue because it cannot load these mods as they are designed for earlier versions. 

Regardless, I will continue without the mods in error and see if it loads anyway. Please provide me a bit of time. 


Edit: Looking again, your debug says you have the appropriate versions, but I do not see them on curseforge. Am I in error? Checking
Edit2: I am in error, continuing

**Comment by StygianNights** [comment]
Okay, made the pack, so it should be easier to test things. so far I am crashing on loadup because of issues with Minecraft comes alive. 
If you could please let me know versions you are using, and please check for a crash report and post it.

**Comment by StygianNights** [comment]
Okay, so after a bit of time looking at the debug log and getting all the proper versions and doing some quick testing, I noticed 4 issues. 

- First, in regards to Enigmatic Legacy, You also have Etherium installed. This causes an immediate issue from what I can see that will prevent minecraft loading. Edit: I forgot to mention, as far as I can tell, Etherium's contents are already in Enigmatic Legacy, so you should be fine to drop it regardless

- Second, the first real roadblock I encountered was allthemodium causing issues whenever a world is deleted or made, which instantly crashed. 

- Third, Sky Villages is not 1.18.1 or 1.18.2, and as such, will not work for either one. Or at least it wasn't for me when I used the version you had installed. 

- Fourth, You were missing a dependency for Additional Enchanted Miner, the mod "ScalableCatsForce". I could not load without this, and only noticed it because it auto installed when I installed Additional Enchanted Miner through curse launcher. 

With all the aforementioned issues resolved, fixed, or removed, I was able to load into singleplayer.

**Comment by keepinitreal247** [comment]
> Okay, so after a bit of time looking at the debug log and getting all the proper versions and doing some quick testing, I noticed 4 issues.
> 
> * First, in regards to Enigmatic Legacy, You also have Etherium installed. This causes an immediate issue from what I can see that will prevent minecraft loading. Edit: I forgot to mention, as far as I can tell, Etherium's contents are already in Enigmatic Legacy, so you should be fine to drop it regardless
> * Second, the first real roadblock I encountered was allthemodium causing issues whenever a world is deleted or made, which instantly crashed.
> * Third, Sky Villages is not 1.18.1 or 1.18.2, and as such, will not work for either one. Or at least it wasn't for me when I used the version you had installed.
> * Fourth, You were missing a dependency for Additional Enchanted Miner, the mod "ScalableCatsForce". I could not load without this, and only noticed it because it auto installed when I installed Additional Enchanted Miner through curse launcher.
> 
> With all the aforementioned issues resolved, fixed, or removed, I was able to load into singleplayer.

Ahhh ok I see thank you so much I should have figured that out when I had never used the Etherieum mod in 1.16.5.....but as for the other things I removed and added everything and now it works just fine! I'm so sorry for taking some time out of your day but I'm glad it was just me being dumb and nothing was wrong with your mod! I've been using it for a while now so I'm glad I'll be able to continue to do so. Thanks for your help!

**Comment by Aizistral** [comment]
Thanks for your work, @StygianNights! I hope my requests to provide help with these issues don't bother you too much.
