### ISSUE TITLE
Arrows reflected with Angel's Blessing Soulstone can always be picked up, even if it was shot by a skeleton

### ISSUE THREAD

**Issue by LTCatt** [Extegral/Enigmatic-Legacy#330]
#### Versions:
 * Enigmatic Legacy: 2.11.12
 * Forge: 1.16.5-36.2.34

Arrows reflected with Angel's Blessing Soulstone can always be picked up, even if it was shot by a skeleton.

**Comment by StygianNights** [comment]
Okay, so I did a bit of testing and thought that honestly that this was a fluke of some kind, but then one of the arrows fired at me hit the cage for the skeleton instead of the boney boy, and I was indeed able to pick it up. 

Went ahead and tested on the most recent version of the mod as well and the bug still exists. Considering the unerring accuracy of the reflected arrows, and the circumstances I had to pull to get this "infinite arrow" farm to work, I don't think it would be a viable way to get loads of arrows, but an exploit is an exploit.  (Works on stray slowness arrows, so it might work on other modded arrows)
Confirmed.
