### ISSUE TITLE
Extradimensional Vessel not holding books of any kind

### ISSUE THREAD

**Issue by vizthex123** [Extegral/Enigmatic-Legacy#351]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.23.1
 * Curios API: 5.0.7.0
 * Patchouli: 1.18.2-69
 * Forge: 40.1.41

#### Description of a Bug:
Whenever I die with a guide book (mainly the Akashic Tome and quest book from FTB Quests), it doesn't go into the extradimensional vessel that spawns when you have the starting amulet equipped.

#### How to Reproduce:
1. Get a guide book in your inventory
2. Equip the Enigmatic Amulet
3. Die

#### Logs:
[latest.log](https://github.com/Aizistral-Studios/Enigmatic-Legacy/files/8912300/latest.log)

**Comment by PikachuGabe** [comment]
Were they in your inv when you respawned?

**Comment by StygianNights** [comment]
I just tested with the latest as of today version of Quintessence (B2.0), the modpack the log indicates. I have died in survival and creative and not encountered the reported issue. Did you make any alterations to config settings, any additional mods, anything at all?
The only thing similar to the issue at all would be that when I die, the FTBQ book always seems to attempt to stay in my inventory, instead of staying in the vessel.

**Comment by vizthex123** [comment]
> I just tested with the latest as of today version of Quintessence (B2.0), the modpack the log indicates. I have died in survival and creative and not encountered the reported issue. Did you make any alterations to config settings, any additional mods, anything at all? The only thing similar to the issue at all would be that when I die, the FTBQ book always seems to attempt to stay in my inventory, instead of staying in the vessel.

Yeah, that issue with the book was mainly what my issue was. I removed the gravestone mod I had to see if that was the problem, and it seems a recent mod update has fixed my issue.
