### ISSUE TITLE
Etherium hotbar crash

### ISSUE THREAD

**Issue by nexus140** [Extegral/Enigmatic-Legacy#36]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.8.2
 * Curios API: 3.0.0.2
 * Forge: 32.0.98

#### Description of a Bug:
when putting the etherium sword in a hotbar in a server it crashes

#### How to Reproduce:
1. ... hop in a server
2. ... and just try to put the etherium sword in the hotbar
3. ...
4. Behold!

#### Logs:

https://pastebin.com/9pZmJ9Vh

https://hastebin.com/venizuheko.md

**Comment by Extegral** [comment]
So, the client crashes, not the server itself, right?

This issue is a good explanation of why I request to reproduce all issues without other unnecessary mods first. The exception that causes the crash doesn't seem to have anything to do with Enigmatic Legacy:

`[ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Registry Object not present: forbidden_arcanus:indestructible`

It appears to be something on the side of Forbidden and Arcanus. Report it to them: https://github.com/stal111/Forbidden-Arcanus/issues
