### ISSUE TITLE
[Feature Request] Add a config option to disable the Enigmatic Amulet on new World Spawn.

### ISSUE THREAD

**Issue by Gbergz** [Extegral/Enigmatic-Legacy#38]
> Add a config option to disable the Enigmatic Amulet on World Spawn.

**Reason**
Currently creating a modpack where I don't want more attack damage and armor when you first spawn in.
And I was going to add a recipe to make the Amulet instead.

I think I've requested this before but it seems like that request has been buried, so I'm requesting this again.
Hoping my request will make it.

Thanks,
**-** Gbergz

**Comment by Extegral** [comment]
I doesn't provide armor stat anymore, since 1.8.3. There is another ability to it, however.

Enigmatic Amulet is a thing that player is intended to possess ever since the beginning of their journey, quite unique, as they have only one. Making it obtainable through crafting recipe would directly contradict it's primary design and lore (latter kind of doesn't exist yet, apart from few tooltip lines, but it will in a couple updates). I am not here to question your modpack design choices, of course, but I wouldn't be going out of my way to make an option that sends initial idea behind an item flying out of the window.

I can add options that would allow to tweak it's attack damage bonus and whether or not it has it's new special ability, however.

**Comment by Extegral** [comment]
> I can add options that would allow to tweak it's attack damage bonus and whether or not it has it's new special ability, however.

Done that in 1.8.6 release.
