### ISSUE TITLE
Can't wear anything excepting charms

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#48]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 1.8.6
 * Curios API: 3.0.0.2
 * Forge: 32.0.108

#### Description of a Bug:
When you take ring, scroll or spellstone it gives you achievement but not unlocked the slot. "How to use" message is not appeared too, only achievement. No other mods used.
PS: It also broke the world for previous mod versions. You can't take the slot because you already have achievement.

#### How to Reproduce:
1. Create new world
2. Take ring, scroll or spellstone
3. ...
4. Behold!

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Extegral** [comment]
Gotta wonder why only now someone decided to report this.

Guess there will be another patch then.

**Comment by Tillllt** [comment]
In 1.8.5 it's all right for me. Strange. Nevertheless I can guess that people play at their old worlds when they already unlocked that slots at previous mod versions.

**Comment by Extegral** [comment]
Through testing I figured out that issue must be in my methods for checking out whether or not slots were locked before, and checks I made using these to make sure that Enigmatic Legacy will not be trying to unlock slots and notifying player that they are unlocked if they are somehow unlocked already - for instance, if another mod also registers ring slots and those slots end up being set to be unlocked by default.

Since unlocked slot are re-enabled on death by checking permanent nbt tag that gets set regardless, however, dying once should   get supposedly unlocked slots to work properly. Check out and report if it works for you.

**Comment by Tillllt** [comment]
Yes it works for me. Slot was unlocked after death.

**Comment by Tillllt** [comment]
Actually 1.8.5 is fine. First i thinked it's bugged too because i created the world in 1.8.6, take ahievement and then opened that world in 1.8.5.

**Comment by Extegral** [comment]
Then my assumptions were correct. I will release a patch in an hour or so, should supposedly not happen anymore and get fixed in any worlds where it occured.

**Comment by Tillllt** [comment]
Nice!
