### ISSUE TITLE
Knockback Resistance for Etherium Armor

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#54]
Every peace of Netherite Armor has +1 Knockback Resistance. Maybe it's fair to add that thing on Etherium Armor too.

**Comment by Aizistral** [comment]
I will consider, but no certainty here. I personally feel like knockback resistance is situationally useful trait that might not always be great to have, and just because netherite armor has it now doesn't mean every armor better than netherite should either.

There will be new set of gear implemented soon that will serve as direct upgrade from netherite available earlier than etherium. Knockback resistance will be present on that armor for certain.

**Comment by Tillllt** [comment]
It seems reasonable, since we have a different situations in game. I just think that it's not good when enemies can push you like they want. But on other side we have Heart of The Golem for that. So yeah.
