### ISSUE TITLE
A thin defect(?) about Blazing Core and other accessories Night Vision status effect

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#60]
**The question.**
When you wear Blazing Core with Night Vision status effect from Charm of Treasure Hunter or from Will of the Ocean it's not remove instantly from you as usual but start ticking twice as fast within 5 seconds. Is it was planned or just a small bug?

**Comment by Aizistral** [comment]
It wasn't intended. I can guess this is because Blazing Core manually ticks the effect second time in game tick, forcing it to skip specific duration that effect is checked for before being removed, so that Night Vision aquired throigh other means, like from drinking potion, is unaffected.

I'd like to close this and ask you to open a separate bug report on this.

**Comment by Tillllt** [comment]
Ok
