### ISSUE TITLE
[1.16] Netherite Armor and Etherium Armor

### ISSUE THREAD

**Issue by LVSCIVIOUS** [Extegral/Enigmatic-Legacy#64]
The 1.16 update introduced Netherite Armor into the game. Since you can find Etherium Dust in End Cities I don't feel like grinding for Netherite because I could just go with Diamond Armor, slay the Ender Dragon and get Ehterium Armor.
It'd be cool if you could, instead of crafting a whole new set of armor, just upgrade Netherite Armor INTO Etherium Armor making a grind for Netherite Armor worth it.

**Comment by Aizistral** [comment]
Etherium armor requires a fair bit of grinding on it's own. I have considered the possibility of making it an upgrade from netherite one, but have dismissed the thought as it has functional differences significant enough from netherite armor that don't really add up from logical perspective.

There will be new material and set of gear soon that will certainly be an upgrade on top of netherite. I will probably try to weave in some of that material into etherium armor recipes, so that while armor itself can be skipped, obtaining ingredients it's crafted from will still be required to put next tier together.
