### ISSUE TITLE
Scroll of Postmortal Recall death crash

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#66]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy: 2.2.0
 * Curios API: 3.0.0.2
 * Patchouli: 1.16-39
 * Forge: 32.0.108

#### Description of a Bug:
Crash after death from neutral mob while wear Scroll of Postmortal Recall in dimension without spawn point. It seems that it's ok with enviromental death or hostile mobs.

#### How to Reproduce:
1. Wear SoPR and go to the Nether (for example).
2. Die from neutral mob.
3. ...
4. Behold!

#### Logs:

[crash-2020-09-15_21.10.23-server.txt](https://github.com/Extegral/Enigmatic-Legacy/files/5226908/crash-2020-09-15_21.10.23-server.txt)
Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Tillllt** [comment]
And no other mods used ofcourse.

**Comment by Tillllt** [comment]
If it helps. It looks like it is on previous versions too. I guess I first encountered this while playing with the cursed ring on.

**Comment by Aizistral** [comment]
This is hella weird. This only happens when player gets teleported to another dimension as a result of recall, and the removal of the player from dimension in process of teleportation seems to cause the problem, but crash itself happens in vanilla code further down the stack, as for whatever reason player entity gets ticked midway in the process of their death. I have no idea why it happens only with death from neutral mobs, and so far see no other way to avoid this apart from changing the implementation completely, so that, for instance, instead of teleporting the player only whatever they would drop in place of their death would get teleported.

I will consider reporting this to Forge repository after further investigation and after I can confirm that it happens on 1.16.3 either.

**Comment by Tillllt** [comment]
> instead of teleporting the player only whatever they would drop in place of their death would get teleported.

In general i think it will be better just like that, at least for map mods. Because for now, every time i die with SoPR, Voxel Map leaves a death mark after teleporting the corpse, and sometimes this makes it difficult to find the scroll.

**Comment by Aizistral** [comment]
I'd be happy to fall back to old mechanic in one form or another anyhow, but my report on the matter was unfortunately pretty much disregarded:
https://github.com/MinecraftForge/MinecraftForge/issues/7365
I sure am irritated by inconsistent bahavior of Minecraft/Forge sometimes, but hopefully it's not as important in this instance, and new implementation of the scroll seems to do the trick so far.
