### ISSUE TITLE
Development mechanics with Ring of the Seven Curses

### ISSUE THREAD

**Issue by Tillllt** [Extegral/Enigmatic-Legacy#70]
It's another large idea so i don't know how much it's possible or even needed.
First i think it needs to make +1 Looting and +1 Fortune like one blessing because it's really thin for two. 
Then add one new blessing: Your own pets becomes stronger after seven days with you. Wolves and cats becomes bigger visually with more dark textures, with double more HP and attack strength and also receive your curent level of XP and loot dropping (attack, xp and loot not for cats ofcourse). Cats has more radius to frighten creepers and can curse enemies with weakness (1 enemy per 10 seconds) within 15 seconds.
Then also add two cursed upgrades to Emblem of the Monster Slayer:
1. Cursed Emblem of the Monster Slayer: +1 Looting, Double XP drop, +5% damage against all aggresive creatures. Player receive +1 extra percent attack boost for each day he's alive with full soul and RotSC weared, up to 80% max, but when he die counter dropped and not starts without full soul (no matter he wears the emblem or not). Your cursed pets cannot live long and will die.
2. Emblem of the Monster Ruler: -30% damage against all aggresive creatures. Player pets get even more HP and attack strength and become immune to suffocation, fire and magic damage. Cats has a regeneration aura (It would be cool if they can purr with that aura working). Small chance to charm any monster while you attacking them. Charmed monsters cannot live long and will die, but attacks other aggresive creatures.

Once player weared one of that cursed charms he can't wear another one.

Also i think you can change a little Pearl of the Void abilities: If player wear RotSC light level becomes zero around him. Cursed pets can't be touched by omnivorous darkness.

**Comment by Tillllt** [comment]
And/Or maybe fuse "Unique drops from some creatures" and "You can create and use unique relics" in one blessing too, because it's actually the same thing and even add attack/mine speed boost like another blessing.

**Comment by Tillllt** [comment]
Some more about: Cursed pets can breeding but with normal puppies and kittens. They can become cursed only after growing up.

**Comment by Tillllt** [comment]
And more: Twisted Mirror can teleport you with cursed pets if they nearby.

**Comment by Tillllt** [comment]
Ok, i take my words back about "Unique drops from some creatures". Now i understand why drowned dropped lapis.

**Comment by Tillllt** [comment]
I just think about it and it seems i'm complicated things again. Maybe it can been simpler compared to all that i writed before. Maybe just add one cursed charm for buff pets and another for buff yourself but with restrictions to have pets, and that's all.

**Comment by Aizistral** [comment]
I certainly look forward to expand RotSC mechanics, with both new curses and new blessings. Of course they cannot be infinitely compacted to fit the cool-looking-number of seven, so it will require either explicitly changing that number, or, as I initially intended, just have the list of curses/blessings in tooltip outline only the most major effects of both types, with the rest remaining unlisted and instead being outlined in ring's entry in The Aknowledgment.

But damn, these ideas of yours are a weird way to expand those mechanics. First and foremost, I won't go pet-related features. They can surely be explained from standpoint of lore and everything, and even make practical sense since pets, unlike bearer of the ring, can deal their full damage to anything. But I don't really like how pets are implemented in Minecraft in general, and rectifying that implementation is a feat in it's own right, which I am unlikely to attempt anytime soon granted how much stuff is already scheduled for further development.

The idea behind cursed emblem is more like it, but there's a catch. I don't think it's a good idea at all to have mechanics with this ring that grant increasing bonuses depending on how long player stays alive, with or without full soul, because the more such bonuses we'll have and the greater is cap for their stacking, the more encouraged players will be for incredibly cautionous and defensive playstyle. And no playstyle is better at this than just sitting at your base and avoiding going into dangerous places, as much as going anywhere at all. Loosing these bonuses for a significant period of time will be a great punishment for taking any potential risks, and players may easily end up optimizing fun out of their gameplay by avoiding any risks whatsoever.

**Comment by Aizistral** [comment]
> Also i think you can change a little Pearl of the Void abilities: If player wear RotSC light level becomes zero around him.

And here I don't think there's a good way to achieve this technically. It may be doable with visual effect that will affect players, similar to blindness, but it would be a weird design anyhow since bearer of the pearl themselves may find trouble discerning their surroundings, which isn't exactly a helpful ability you'd expect from like the single rarest item in the whole mod.

**Comment by Aizistral** [comment]
> And more: Twisted Mirror can teleport you with cursed pets if they nearby.

Okay, I said I won't go for pet-related features, but I wouldn't mind implementing this one for all tamed animals in general.

...probably.

**Comment by Tillllt** [comment]
Understood, probably it's really weird way for some cursed build through pets and i'm realy not thinked that people can just afk to receive cursed emblem full power like that. Maybe other concept can work with this? Like if players needs to powerup cursed emblem with some rare material on smithing table.
Also for now End is very tough thing to deal with that ring. Because you need to take with you many ice or buckets of water against the endermen to defeat the dragon and build a flying piston machines to get elytra. Maybe it needs to change mechanic that would make them aggressive? For example chance to make neutral mob aggressive to you in anytime, that is to say not all of them and just random ones. Or maybe make some radius within which they will become hostile?

**Comment by Aizistral** [comment]
> Or maybe make some radius within which they will become hostile?

That is a thing already. Mobs are instantly angered within 32 blocks radius from player, any further they behave like normal. Needless to say though, 32 blocks is a lot of blocks, and some consideration after I can agree that it may make sense to decrease this radius to like 16 or something.

The End being tough as hell to get through is something I initially intended, however. Whichever way players who bear this ring approach a titanic feat alike this is up to them, but they are free to push anything they can manage to the limit in pursuit of victory. Some will inevitably give up, but I guess many stories this ring will be a part of won't have a happy end. That's its design, after all.

**Comment by Tillllt** [comment]
> Needless to say though, 32 blocks is a lot of blocks, and some consideration after I can agree that it may make sense to decrease this radius to like 16 or something.
> The End being tough as hell to get through is something I initially intended, however.

If The End was intended to be like that with a ring then i guess it needs some testing with 16 blocks. So that this would not "easy" within 16 blocks, maybe it even will need a bit more.

Speaking of Cursed Emblem. What if players need to permanently kill aggressive creatures to boost that and so power fades away with time if they not?
Or maybe even make "Emblem of the Berserk" that buff player's damage when he lose HP. So it amplifies to max when he lives with half a heart. But then it maybe need to add some "Curse of hurting" enchantment for weapons, that damage the player when he use that cursed weapon (but can't die of it). Or just add that feature on the Berserk Emblem. Or players can drink poison potions for that effect. Because to allow monsters hit yourself for charging is not good idea with double damage taking.
I think the key here is to make the cursed player feel yourself stronger than the non-cursed player. But the playstyle must be very aggressive for that.
Actually, you could close this issue if this is not necessary. In the end, maybe you have some other ideas at all about the cursed mode.

**Comment by Tillllt** [comment]
I figured what can fit like a blessing for cursed ring. If player use items with cursed enchantments it gives him some benefits. For example attack speed, mine speed and/or just speed for each cursed enchantment.

**Comment by Aizistral** [comment]
> Actually, you could close this issue if this is not necessary. In the end, maybe you have some other ideas at all about the cursed mode.

I am not in hurry to once and for all dismiss any of the ideas that were discussed here. It's something I'll have to look through once again when I actually start working on the next update, as for a while my mind is more focused on other things.

> Speaking of Cursed Emblem. What if players need to permanently kill aggressive creatures to boost that and so power fades away with time if they not?
Or maybe even make "Emblem of the Berserk" that buff player's damage when he lose HP. So it amplifies to max when he lives with half a heart. But then it maybe need to add some "Curse of hurting" enchantment for weapons, that damage the player when he use that cursed weapon (but can't die of it). Or just add that feature on the Berserk Emblem. Or players can drink poison potions for that effect. Because to allow monsters hit yourself for charging is not good idea with double damage taking.
I think the key here is to make the cursed player feel yourself stronger than the non-cursed player. But the playstyle must be very aggressive for that.

These are some actually good ideas. The one about Cursed Emblem is unfortunately very exploitable though, since mob farms have existed for seemingly as long as mobs themselves, and power boosts provided by such mechanic will be easily stackable with simple spawner farm at player's disposal, 100% safe and 100% boring. That can be avoided by having those boost quickly stackable but very short-lived, but I'm not really sure how meaningful it will be then.

Emblem of the Berserk is more like it, and curse of hurting writes well into this equation. I will likely implement both of those.

> I figured what can fit like a blessing for cursed ring. If player use items with cursed enchantments it gives him some benefits. For example attack speed, mine speed and/or just speed for each cursed enchantment.

This also is a pretty good one. I think such boosts will need to have some hard cap to them since we'll probably want to account for curses on wearables and curses added by other mods, but both vanilla curses and the one for weapons named earlier are fairly punishing on their own, so with this ring's themes in mind it makes sense to provide some upside for intentionally having them on your gear.
