### ISSUE TITLE
[1.16.3] Patchouli book doesn't contain any information

### ISSUE THREAD

**Issue by Excederus** [Extegral/Enigmatic-Legacy#74]
#### Versions:
 * Enigmatic Legacy: 2.4.0
 * Curios API: 4.0.2.0
 * Patchouli: 44
 * Forge: 34.0.17

#### Description of a Bug:
The Patchouli book does not contain any information about any entries in it (the entries itself are displayed - it also highlights new entries with the exclamation mark)

#### How to Reproduce:
1. Install mods
2. Create a random world
3. Check latest.log and/or the Patchouli book
4. Behold!

#### Logs:
latest.log
https://hastebin.com/howufojemo.sql
toml file (maybe relevant?)
https://hastebin.com/coralicoke.shell

**Comment by Aizistral** [comment]
```
Caused by: java.lang.NullPointerException
	at com.integral.enigmaticlegacy.handlers.AdvancedBrewingRecipeProcessor.setup(AdvancedBrewingRecipeProcessor.java:53) ~[?:2.0]
	...
```

Hello darkness my old friend

**Comment by Excederus** [comment]
So is it something on my end? I don't really get that comment tbh.

**Comment by Aizistral** [comment]
I do not know yet, but that NullPointerException often means that I screwed something up again

**Comment by Excederus** [comment]
Ah ok. Good to know

**Comment by Aizistral** [comment]
It's very convenient that you provided your config file. The error seems to happen because you disabled the haste potion in the config, and component processor that bears responsibility for displaying brewing recipes in The Aknowledgment cannot find this potion's recipe, throwing NullPointerException and screwing up the process of loading book's content. For whatever reason I haven't accounted for the fact that some brewing recipes can be disabled through config when making that proccessor, and didn't add exception handling where it should've been present.

Will be fixed in next update.

**Comment by Excederus** [comment]
Hah. Me 5 steps ahead.
Good to know it will be fixed next update. Trying to do anything in the mod to test how it works, but I can't figure out anything without the book. xD

**Comment by Aizistral** [comment]
You can always... you know... just temporarily enable Haste potions back, until it's fixed.
