### ISSUE TITLE
Proper archival of data on Extradimensional Vessel/Soul Crystal spawn

### ISSUE THREAD

**Issue by LilLilyVeryLil** [Extegral/Enigmatic-Legacy#78]
**Provide a detailed and clear description of feature or change that you want to offer.**

**Describe why you want this. If there's a reason.**
I play with keepinventory so when i die i dont loose anything, just my heart...somewhere. I traveled thousands of blocks and died somewhere, im completely lost as to where the heart is. At this point the amulet not only serve no purpose but actually harms me by torturing me into  thinking where possibly i could have died. Is there a possibility to see where the vessel is and would it be possible to turn off that feature completely if i want to?

**Comment by Aizistral** [comment]
Soul loss mechanic exists independently from Enigmatic Amulet's ability. By default, it only affects players who bear Ring of the Seven Curses, and lost soul crystals remain in place of their death regardless of whether or not keepInventory is enabled. Having Enigmatic Amulet on you just wraps the crystal within Extradimensional Vessel along with normal items dropped along, which ultimately changes nothing if normal items do not drop at all, since both Soul Crystals and Extradimensional Vessels act identically as entities.

I generally rely on players who choose to bear the ring having some kind of deathpoint thing in their modpack, or at least realizing what possible consequeces might befall them otherwise. But in future, it would be fair to properly archive the data on where crystals/vessels are spawned when it happens, in some accessible form. In the meantime, any time either crystal or vessel is summoned for player, it is actually printed to game log file along with coordinates of this event. You can locate your log files in "logs" folder within your Minecraft installation directory. Most of them are stored in .gz archives named accordingly to the date when they were written, so if your death happened a while ago, you'll have to look through the files by date. Within .log files stored within each archive, you're looking for messages like this:

```
[06Sep2020 20:14:55.195] [Server thread/INFO] [Enigmatic Legacy/]: Teared Soul Crystal from Dev at X: -18.64255390767987, Y: 63.0, Z: 95.79386486321802
```
```
[06Sep2020 20:43:21.579] [Server thread/INFO] [Enigmatic Legacy/]: Summoned Extradimensional Vessel for Dev at X: 2725.642383717887, Y: 35.0, Z: -124.73716386321802
```
