### ISSUE TITLE
Include the seven curses of the Ring of the Seven Curses in the Scroll of a Thousand Curses

### ISSUE THREAD

**Issue by llssc** [Extegral/Enigmatic-Legacy#84]
Instead of just including enchantment curses, the scroll should also include the curses of the ring, possibly at the cost of nerfing the stats of the scroll.

**Describe why you want this. If there's a reason.**
It is weird since those curses are not counted as curses even though the ring's tooltip says they are curses.

**Comment by Aizistral** [comment]
Well, they aren't cursed enchantments which I initially intended to be meant as curses that this scroll is powered by. I should probably have made the wording more clear, but... It's actually an interesting idea to make it the way you suggest, as it both adds consistency and actually makes scroll useful without the need to put some more curses on your gear first, which won't be overpowered since the price of possessing this scroll is to deal with all suffering brought upon you by Ring of the Seven Curses. Maybe it will indeed require to correct stats received for each curse a bit, but likely not much even.
