### ISSUE TITLE
Might be a bug report, might be me misreading a feature.  Either way, currently unable to prevent players from spawning with the Enigmatic Amulet.

### ISSUE THREAD

**Issue by Inpaladin** [Extegral/Enigmatic-Legacy#86]
* Enigmatic Legacy: 2.6.1
 * Curios API: 4.0.2.0
 * Patchouli: 1.16.2-44
 * Forge: 34.1.0

I have EnigmaticAmuletEnabled set to false and still spawn with the Enigmatic Amulet in a new world.  It might be worth noting that it only gives the amulet once I've been granted spawn advancements included in other mods.  Don't worry, I reproduced the behavior in a separate minecraft instance with the same config and just patchouli, curios, and EL installed.

Image of amulet with my name
![image](https://user-images.githubusercontent.com/59532097/96223014-19cc2700-0f42-11eb-80c3-0cefd3c0f7b3.png)

**Comment by Aizistral** [comment]
The option to disable it does currently not affect anything, since as mentioned in the category header, it's generated automatically and some of options in that category may not work. Why would someone want to disable the amulet?

**Comment by Inpaladin** [comment]
> The option to disable it does currently not affect anything, since as mentioned in the category header, it's generated automatically and some of options in that category may not work. Why would someone want to disable the amulet?

not sure how github notifications work so I hope you'll see this!  For my purposes, it's just kind of clutter.  In the modpack I'm working on I don't want players to spawn any more powerful than they normally are, so as of now it's basically just a useless item.  
I was also thinking about adding some sort of very light lore to the modpack and feel that the flavor text on the amulet would slightly conflict with it.  I do like adding flavor to the game, so I wouldn't mind it as much if it wasn't for that.

**Comment by Aizistral** [comment]
> not sure how github notifications work so I hope you'll see this

I am watching my own repository, and thus am notified of any new comments left anywhere within it, should it be even a year old closed issue.
'ight, I will make this option work. Reason I didn't want to is because I might add some content in the future that relies on the fact that players will possess the amulet soon as they enter the world. I won't extensively account for the possibility of amulet being disabled with such content, but guess modpack creators know what they're doing and will figure out what to do about it, if anything at all.

**Comment by Inpaladin** [comment]
For sure, thank you.  Honestly the more configurability the better.  That's why I love quark and this mod so much, I can fit them into just about anything and adjust them accordingly.  Appreciate it!

**Comment by Aizistral** [comment]
> Honestly the more configurability the better

That is true, but so is the fact that it's difficult to keep weaving in more configurability the more you expand inner progression of the mod and the more intertwined different elements of that progression are, because at some point the amount of interactions you need to account for becomes way too overwhelming to handle. Simple example, without even any progression taken into account - I can take an item and make one of it's abilities disableable through config, but then there is tooltip that states item should have this ability, and there is it's entry in The Acknowledgment that might also refer to it. Disabling specific part of the tooltip along is not difficult, but I can't make endless edits of entries in book for every possible combination of enabled/disabled abilities, and I am 150% certain no modpack developer will bother editing it either. 

Configurability is much easier to do with collection of unrelated utilities, where some of them may be dismissed without affecting other ones in any way, and where there is no guidebook to account for and no lore to speak of.

**Comment by Inpaladin** [comment]
Feature creep, basically.
