### ISSUE TITLE
Friend lost his grave and his soul due to a bug.

### ISSUE THREAD

**Issue by wrachilles** [Extegral/Enigmatic-Legacy#87]
Are there any commands to return his lost hearts to him? He's down 3 hearts currently and it was nothing he could prevent, it was a bugged nether portal that was killing my upon entry.

**Comment by wrachilles** [comment]
Sorry, I'm also a complete dingus, and this is referring to the ring of seven curses.

**Comment by Aizistral** [comment]
You can get soul crystal as an item with give command (enigmaticlegacy:soul_crystal). Right-clicking with it restores as much health as one crystal lost has taken.

But soul crystals spawned in place of death are supposed to be indestructible and undespawnable, whether in form of soul crystals or stored within extradimensional vessel. How could they possibly have vanished?

**Comment by wrachilles** [comment]
Alright, awesome, thanks! We actually aren't sure ourselves. We're playing a modpack on the ATLauncher called Filmpack and when we went to the nether, we got chased around by endermen, they all slammed into our portal, there was 5 of them, and when we went back to deal with them, he suffocated in the wall while I killed the endermen. Ever since then, whenever he went through the portal he repeatedly suffocates in the wall, even with a new portal. It's a problem we can't seem to nail down.

**Comment by wrachilles** [comment]
I have fully dug and isolated around both nether portals and neither his grave, nor the soul gem can be found.

**Comment by Aizistral** [comment]
Would be helpful if you checked the log files to see the exact coordinates where crystals should have spawned. You can locate your log files in "logs" folder within your Minecraft installation directory, or server directory if you were on dedicated server. Most of them are stored in .gz archives named accordingly to the date when they were written, so if deaths happened a while ago, you'll have to look through the files by date. Within .log files stored within each archive, you're looking for messages like this:

```
[06Sep2020 20:14:55.195] [Server thread/INFO] [Enigmatic Legacy/]: Teared Soul Crystal from Dev at X: -18.64255390767987, Y: 63.0, Z: 95.79386486321802
```
```
[06Sep2020 20:43:21.579] [Server thread/INFO] [Enigmatic Legacy/]: Summoned Extradimensional Vessel for Dev at X: 2725.642383717887, Y: 35.0, Z: -124.73716386321802
```

Re-check specific coordinates you will see in both dimensions and report back if there's anything there.

I suspect possible cause might be due to the fact crystals still can be moved between dimensions if they end up within portal, which I will fix in the next update.

**Comment by wrachilles** [comment]
I'll give a quick check shortly and update you accordingly.

**Comment by wrachilles** [comment]
According to the coordinates, it is both making the grave (not sure if it's the same mod) as well as the soul crystal on the portal block. So I guess your assumptions are indeed correct.
