### ISSUE TITLE
Lore scroll writing disappears when item placed

### ISSUE THREAD

**Issue by Oscar-the-Khan** [Extegral/Enigmatic-Legacy#88]
I am on a friend's modded server. We are using 
TNP unlimited 3 Version: 1.6.0 (there are currently 2 subsequent releases). 
The version of EL that I am using is 1.14.4

I used the Architect's Inkwell to create a Lore Scroll and the anvil to assign it to an item (I tried a regular bed, and a dark oak mailbox from Mr Crayfish's Furniture Mod) but when I placed the items on the ground, they were no longer labelled with the lore. When I picked them up again they were still unlabelled with the lore.

Are there any known issues/conflicts with other mods that could be causing this?

**Comment by Aizistral** [comment]
This is not a bug, nor a conflict, but simply a limitation of how vanilla is designed, therefore inherited by mods. If you're interested in technical side of things, blocks cannot exist within inventory or dropped as item on their own - what is cosidered block does only exist within the world, reserving it's 1x1x1 cubic meter of space for itself. What exists in your inventory is just an item that is supposed to represent the block, and when you right-click with it to place it down, what happens in the code is that item is basically deleted, and block associated with it is created in the world.
This transformation does not neccessarily preserve all properties of the item. Most itemblocks will have their NBT erased when placed as actual blocks, because the block itself simply isn't supposed to store any kind of NBT data and thus it is never accounted for. In order for that data to be preserved, each block needs to be programmed to do so. Some vanilla blocks are made to do this, for instance banners, shulker boxes or chests, since they require that in order to hold their innate properties, like color patterns of banners for instance, and thus often times they may conveniently copy over entire NBT tag. It is possible however that some part of that tag might be copied and some dropped, like custom block name might be preserved while lore lines erased. You can check if block can hold at least name by just renaming it in the Anvil without inkwell involved, and then placing it down and breaking. If name didn't persist, nothing that comes from attachment of Lore Fragment will either.

Display data attached with Lore Fragments is actually a completely vanilla mechanic, just EL allows to access it without commands and use formatting codes without NBT editor.
