### ISSUE TITLE
Did you physically prevent equipping multiple spellstones at the same time?

### ISSUE THREAD

**Issue by llssc** [Extegral/Enigmatic-Legacy#94]
**The question.**
I had spent weeks to complete all spellstone collection and unlock 6 slots with config to use their passive, but after updating to 2.7.1, I found out that I cannot equip a spellstone that I had taken off previous day. 
Is this intended? I suppose it is. Any plan of reverting or adding to config for multiple spellstones?

**Comment by Aizistral** [comment]
Yes, it is indeed intended. Apart from carefully timing this change specifically to mess with you, it was also made in the light of feature I suggested on Curios repository possibly being implemented: https://github.com/TheIllusiveC4/Curios/issues/78

[TheIllusiveC4](https://github.com/TheIllusiveC4) did confirm he will implement this whenever he has time when I asked him on his Discord server, so ahead of time I made a couple changes to how certain wearables check whether or not they can be equipped, accounting for the possiblity of there once being more slots accepting them than I thought there ever will be.

I don't want to allow equipping more than one spellstone at a time by default because they were designed as "pick one" tools, powerful yet situational. Most spellstones are heavily stacked on passive traits, and allowing even two at once is already OP in my mind, at least by the measures of vanilla which I try to work from. Furthermore, the way they are currently programmed simply doesn't account for the possibility of there being more than one, and in scenario when multiple spellstones are equipped some of the traits simply will not work, while others will, with no order or consistency to this and no clear indication on which ones do and do not work prompted to user.

I can add a config option that allows to revert change I made in 2.7 if you really want me to, just don't expect any compatibility or support for such behavior within the mod.

**Comment by Aizistral** [comment]
I made the option, hopefully this closes the case.

**Comment by dylanroberts132** [comment]
how would i add a new slot for spellstones after i set multiple to true?

**Comment by Aizistral** [comment]
https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users
