### ISSUE TITLE
Orb of Oblivion bug

### ISSUE THREAD

**Issue by 2el222** [Extegral/Enigmatic-Legacy#98]
#### Versions (Be specific, do not write "latest"):
 * Enigmatic Legacy:2.7.3
 * Curios API:4.0.2.0
 * Patchouli:47
 * Forge:34.1.35

#### Description of a Bug:
Orb of Oblivion doesnt add items to its list

#### How to Reproduce:
1. Adding items thru crafting doesnt work, list is always empty
2. Sometimes item can be added, but it gets removed after u add another one and it clears the list, its very easy to reproduce, and no other mod blocks or items were used
3. ...
4. Behold!

#### Logs:

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by Aizistral** [comment]
I cannot reproduce this. I use exact same versions you specified, but everything works fine in my instance:

![image](https://user-images.githubusercontent.com/47505981/97991179-5b355100-1de1-11eb-8aae-122e891255ce.png)

**Comment by 2el222** [comment]
Ohh, thats my bad, I had an item of one mod that I removed in the list and it somehow crashed all of the oblivions I made in the  world, but it seems to be working after optimizing, sorry for trouble

**Comment by 2el222** [comment]
Still happening, even on a new world...
![2020-11-03_16 19 30](https://user-images.githubusercontent.com/54117086/97996700-c33f6380-1df0-11eb-8ddf-6705eb5c9ecb.png)
![2020-11-03_16 19 40](https://user-images.githubusercontent.com/54117086/97996711-c63a5400-1df0-11eb-8694-e4f436d08b5b.png)

**Comment by Aizistral** [comment]
This is why I ask to reproduce with no excessive mods before reporting. Since it works fine in my fresh instance, I can only assume this is caused by behavior of some other mod, but I obviously do not have access to your modpack, nor time to do all the debugging for you.

Test with no other mods first. If it indeed works fine as in my instance, take your modpack and use classical method of splitting it to nail down the mod causing this. Then report back here, once I know what specific mod is responsible for this I will see whether anything can be done on my side to fix this.

**Comment by Aizistral** [comment]
Closing this since no reply followed. Bump if the issue is still relevant, will re-open.
